### ISSUE TITLE
Cannot run saltstack modules sucessfully.

### ISSUE THREAD

**Issue by sujuanliu** [StackStorm-Exchange/stackstorm-salt#2]
Hey guys,
 
I got an issue when running saltstack modules in ST2 web console, it seems all of saltstack modules cannot be run successfully. Does python 2.7 is too old for st2? Can you help? I am looking forwarding to ur reply. Thanks.
 
Environment information:
St version: st2 2.2.1
St2client:Version: 2.2.1
Python version: Python 2.7.6
OS: Linux VM-27-161-ubuntu 3.13.0-105-generic #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 
Issue description:
When trying to run saltstack module via st2 web console and st2 server, I got the below errors: I got salt master and ST2 installed on the same box.

Running `st2 run salt.local module=test.ping` command on the server, still got the same error:

```
id: 5908609f43ff0a1b5eceff26
status: failed
parameters: 
  module: test.ping
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/salt/actions/local.py", line 35, in run
    data=kwargs)
  File "/opt/stackstorm/packs/salt/actions/lib/base.py", line 62, in generate_package
    clean_payload = sanitize_payload(('username', 'password'), self.data)
  File "/opt/stackstorm/packs/salt/actions/lib/utils.py", line 67, in sanitize_payload
    map(lambda k: data.update({k: "*" * len(payload[k])}), keys_to_sanitize)
  File "/opt/stackstorm/packs/salt/actions/lib/utils.py", line 67, in <lambda>
    map(lambda k: data.update({k: "*" * len(payload[k])}), keys_to_sanitize)
TypeError: object of type 'int' has no len()
"
  stdout: ''
```

**Comment by warrenvw** [comment]
I am able to reproduce this issue in `st2-docker` environment with one minor difference:

I see `TypeError: object of type 'NoneType' has no len()` instead of `TypeError: object of type 'int' has no len()`. Here's the content of `payload` in my environment - does it differ in your environment?

```
{   'client': 'local',
    'eauth': None,
    'expr_form': u'glob',
    'fun': u'test.ping',
    'password': None,
    'tgt': u'*',
    'username': None}
```

**Comment by sujuanliu** [comment]
The value of payload in my env as belows, it looks same as yours. but do you know how to resolve the issue?
```
 {'username': '**********',
 'expr_form': u'glob',
 'eauth': 'pam', 
'tgt': u'*',
 'fun': u'test.ping', 
'password': '********',
 'client': 'local'}
```

**Comment by lakshmi-kannan** [comment]
@sujuanliu Please try the fix I posted in my PR. I am surprised that an int payload is being thought of as "sensitive" and the function there is trying to mask it. You can use "print" statement to figure out which "int" parameter is being masked. Anyways, I think the patch should fix the issue you see. I'll keep the PR in WIP until you confirm.

**Comment by sujuanliu** [comment]
thanks. I will verify the fix and let you know the results.

**Comment by lakshmi-kannan** [comment]
@sujuanliu Any updates?

**Comment by sujuanliu** [comment]
sorry for the late. I've verified the fix and now i can run salt module successfully.  Thanks for your fix and time. Appreciate!

**Comment by sujuanliu** [comment]
BTW, are there any docs for StackStorm and SaltStack? The only one doc i found is https://stackstorm.com/2015/07/29/getting-started-with-stackstorm-and-saltstack/.

**Comment by LindsayHill** [comment]
I think that blog plus the pack README are the only docs I'm aware of. Happy to take suggestions on any improvements needed (or PRs)
